services:
  frontend:
    build: frontend
    ports:
      - 5000:80
  backend:
    build: backend
    ports:
      - 8000:8000
    volumes:
      - whisper_models:/root/.cache/whisper/
volumes:
  whisper_models:
